### ISSUE TITLE
[Idea] Add name database

### ISSUE THREAD

**Issue by Nalyienf** [ls-/ls_Wishlist#1]
Hey,

first great addon. I hope you can add the name database for the items. That would be great.

Have a nice day !

**Comment by ls-** [comment]
Hi and thank you!

Buuuut... What do you mean by item name database? :sweat: That's a bit vague, hehe...

**Comment by Nalyienf** [comment]
Yes i thought the item name db. But does not matter. It is also without the db a really good addon.

Thank you :)

**Comment by Nalyienf** [comment]
Yes i thought the item name db. But does not matter. It is also without the db a really good addon.

Thank you :)

Yes, that's what I mean

**Comment by ls-** [comment]
TBH, creating such DB is a slow and resourceful process, I'm not gonna do it manually, so it'll be a huge for loop, that cycles through all IDs from 1 to at least 2m. What makes it even worse is that [GetItemInfo](http://wow.gamepedia.com/API_GetItemInfo) function may be quite laggy and often returns ```nil```, so I have to listen to specific event to finally get item info T_T

I was thinking about implementing search by item link, you shift-click an item or link in your chat, then it appears in editbox and addon does its thingy.

**Comment by Nalyienf** [comment]
Yes searching by item link is an good idea ! Hope you can get it.

Thank you for the reply :)

**Comment by ls-** [comment]
Cool, have a nice day!

**Comment by ls-** [comment]
Added with 02c8cae4b87738456032abf46c7d9ab6eb472e24.

Usage is described in commit message.

Right now you can shift-click any item in AH, bags, bank or item links in your chat window, addon will parse them and extract item ID.
