### ISSUE TITLE
Item Tracker to Use the Objective Tracker

### ISSUE THREAD

**Issue by Jayshua83** [ls-/ls_Wishlist#2]
Is it possible for the Wishlist Item Tracker to use the Blizzard Objective Tracker much like PetTracker addon does?

**Comment by ls-** [comment]
Hey!

TBH, I looked into it some time ago, and I may built it in default OT in the future.

I'm working on a new feature for ls: UI and possible a new addon right now, so I prefer to focus on one task at a time.

But there you have it, it's possible to do so and I'm planning to implement it as an option.

**Comment by ls-** [comment]
Done.
