### ISSUE TITLE
Option to Hide / Show Minimap Icon

### ISSUE THREAD

**Issue by greven** [ls-/ls_Wishlist#3]
Hi ls, I've written on WoWInterface but I guess it is easier for you to keep track here.

So the idea is to add an option to hide the minimap icon and ability to show frame with a slash command. That way I can bind it to a macro for instance.

Thanks, keep up the great work!

**Comment by ls-** [comment]
Sup, yeah, I saw it there.

I'm working on another feature right now, but I may add it in the future.

I'm thinking about optional automatic mode. In this mode button is always hidden, but appears to notify you about newly collected item, and then disappears again.

**Comment by greven** [comment]
That would work too. 
I'm a picky fella, I basically strip any addons from the minimap since I run a square config and it's ugly having buttons around it. :)
Thanks for considering it.

**Comment by ls-** [comment]
Done.
